version: "3"
services:
  web:
    image: "steptw/sauron"
    ports:
     - "3010:3010"
    env_file:
     - sauron_variables.env
    volumes:
     - /apps/sauron/projects_config.json:/usr/src/app/projects_config.json
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - /docker-volumes/sauron/rabbitmq:/var/lib/rabbitmq
  mongodb:
    image: "mongo"
    volumes:
     - /docker-volumes/sauron/mongodb:/data/db